{
 "title": "Dynamo Dashboard",
 "description": "Various stats, from Dynamo runtime, GPU HW, NATS, etcd, ...",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Frontend Requests / Sec",
   "type": "timeseries",
   "description": "dynamo_frontend_requests_total (1m)",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(dynamo_frontend_requests_total[30s])",
     "legendFormat": "{{request_type}}, {{status}},"
    }
   ]
  },
  {
   "title": "Frontend Avg Time to First Token",
   "type": "timeseries",
   "description": "dynamo_frontend_time_to_first_token_seconds (sum/count)",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "1000*(dynamo_frontend_time_to_first_token_seconds_sum/dynamo_frontend_time_to_first_token_seconds_count)",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Frontend Avg Inter-Token Latency",
   "type": "timeseries",
   "description": "dynamo_frontend_inter_token_latency_seconds (sum/count)",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "1000*(dynamo_frontend_inter_token_latency_seconds_sum/dynamo_frontend_inter_token_latency_seconds_count)",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Frontend Avg Request Duration",
   "type": "timeseries",
   "description": "dynamo_frontend_request_duration (sum/count)",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "1000*(dynamo_frontend_request_duration_seconds_sum / dynamo_frontend_request_duration_seconds_count)",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Frontend Avg Input/Output Sequence Length",
   "type": "timeseries",
   "description": "The length is the number of tokens. dynamo_frontend_input_sequence_tokens",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "dynamo_frontend_input_sequence_tokens_sum / dynamo_frontend_input_sequence_tokens_count",
     "legendFormat": "ISL"
    },
    {
     "expr": "dynamo_frontend_output_sequence_tokens_sum / dynamo_frontend_output_sequence_tokens_count",
     "legendFormat": "OSL"
    }
   ]
  },
  {
   "title": "DCGM GPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "targets": [
    { "expr": "DCGM_FI_DEV_GPU_UTIL", "legendFormat": "{{__name__}} (%)" },
    { "expr": "DCGM_FI_DEV_POWER_USAGE", "legendFormat": "{{__name__}} (Watts)" }
   ]
  },
  {
   "title": "dynamo.vllm bytes / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(dynamo_component_response_bytes_total{dynamo_endpoint=\"generate\"}[1m])",
     "legendFormat": "Response bytes"
    },
    {
     "expr": "rate(dynamo_component_request_bytes_total{dynamo_endpoint=\"generate\"}[1m])",
     "legendFormat": "Request bytes"
    }
   ]
  },
  {
   "title": "dynamo.vllm requests / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "targets": [
    {
     "expr": "rate(dynamo_component_requests_total{dynamo_endpoint=\"generate\"}[1m])",
     "legendFormat": "__auto"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "dynamo.vllm Avg Request Duration (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "dynamo_component_request_duration_seconds_sum / dynamo_component_request_duration_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "dynamo.vllm Avg Errors / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "targets": [
    {
     "expr": "rate(dynamo_component_errors_total{dynamo_endpoint=\"generate\"}[1m])",
     "legendFormat": "{{error_type}}"
    }
   ]
  }
 ]
}